server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: "optional:consul:"

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 15s
        prefer-ip-address: true
      config:
        enabled: true
        format: YAML
        prefixes: config
        default-context: application
        profile-separator: ','

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id : user-service
          uri: lb://user-service
          predicates: Path=/api/v*/users/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
