server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: "consul:"
    activate:
      on-profile: local

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 15s
        prefer-ip-address: true
      config:
        enabled: true
        format: key_value
        prefixes: config
        default-context: application
        fail-fast: true

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates: Path=/api/v*/users/**
          filters:
            - RewritePath=/api/v*/users/(?<segment>.*), /$\{segment}
            - AuthenticationFilter

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /users/v3/api-docs
    use-root-path: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always