services:
  consul-server: # 서비스 이름
    image: hashicorp/consul:latest      # 어떤 이미지 사용할지
    container_name: consul-server       # 컨테이너 이름 설정
    restart: always                     # 컨테이너가 종료되면 자동으로 재시작
    volumes: # 볼륨 설정
      - consul-data:/consul/data
      - consul-config:/consul/config
    ports: # consul 관련 port
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    command: >                          # > 이걸 통해서 줄바꿈해도 한줄로 인식
      agent -server
      -bootstrap-expect=1
      -ui
      -node=consul-server
      -bind=0.0.0.0
      -client=0.0.0.0
      -data-dir=/consul/data
      -config-dir=/consul/config
      -enable-script-checks=true
      -log-level=info
      -retry-join=consul-server
    networks:
      - microservice-network

  user-db:
    image: mysql
    container_name: user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - microservice-network

  config-server:
    build:
      context: ../config-server
      dockerfile: Dockerfile
    container_name: config-server
    restart: always
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=123asd123asd123asd123asd123asd123asd123asd123asd123asd123asd123asd


  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500
    depends_on:
      - consul-server
    networks:
      - microservice-network

  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500
      - DB_USERNAME=user
      - DB_PASSWORD=user
    depends_on:
      - api-gateway
    networks:
      - microservice-network

volumes:
  consul-data:
  consul-config:
  user-db-data:

networks:
  microservice-network:
    driver: bridge